### ISSUE TITLE
`Render()` and `RenderBytes()` fail if there exist an unrelated file that matches the style name

### ISSUE THREAD

**Issue by mislav** [charmbracelet/glamour#72]
Invocations like `Render(input, "dark")` or `RenderBytes(input, "auto")` will fail with JSON parsing error if the current directory contains files named `dark` or `auto` that are _not_ JSON style files.

This is surprising because I had expected that passing a built-in style as argument will always use that style and _not_ consult the filesystem. I feel that the default behavior of first reading files from filesystem is risky and should rather be opt-in from the user via `WithStylePath`.

As a workaround, I do not use either `Render()` nor `RenderBytes()`:
```go
tr, err := glamour.NewTermRenderer(glamour.WithStandardStyle(style))
tr.Render(text)
```

**Comment by muesli** [comment]
@mislav Thanks for the report! You're right, that was a bad design decision we introduced trying to remain backwards-compatible with previous behavior. @jessemillar has already provided a work-around in #73 that looks sensible.

Since glamour is still fairly young I'm pondering breaking the API here to improve the situation. Should we go down that route, I'll open a PR in cli/cli to prevent future breakage.

**Comment by mislav** [comment]
The workaround looks great! Thank you @jessemillar @muesli 🙇
